-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `year_col`, DROP COLUMN `date_col`, DROP COLUMN `binary_col`, DROP COLUMN `varbinary_col`;
-- 测试一次删除时间与二进制混合类型列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `year_col`, DROP COLUMN `date_col`, DROP COLUMN `binary_col`, DROP COLUMN `varbinary_col`;
-- @TIMER_END
