-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `varchar_col`, DROP COLUMN `varchar_col`;
-- 测试同一语句重复删除同一列时报错的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `varchar_col`, DROP COLUMN `varchar_col`;
-- @TIMER_END
