-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP FOREIGN KEY `fk_drop_col_self_ok`, DROP COLUMN `ref_id_ok`;
-- 测试同一语句先删除外键再删除外键列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `ref_id_ok` INT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD CONSTRAINT `fk_drop_col_self_ok` FOREIGN KEY (`ref_id_ok`) REFERENCES `{{TEST_TABLE_NAME}}` (`id_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP FOREIGN KEY `fk_drop_col_self_ok`, DROP COLUMN `ref_id_ok`;
-- @TIMER_END
