-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `int_col`;
-- 测试删除被单列 CHECK 约束引用的列时自动移除约束的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD CONSTRAINT `chk_drop_col_single` CHECK (`int_col` >= 0);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `int_col`;
-- @TIMER_END
