-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bit_col`, DROP COLUMN `timestamp_col`;
-- 测试一次删除 bit 和 timestamp 列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bit_col`, DROP COLUMN `timestamp_col`;
-- @TIMER_END
