-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bigint_col`;
-- 测试删除被存储生成列依赖的基础列时报错的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `bigint_stored` BIGINT GENERATED ALWAYS AS (`bigint_col` + 1) STORED;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bigint_col`;
-- @TIMER_END
