-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bigint_virtual`;
-- 测试删除虚拟生成列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `bigint_virtual` BIGINT GENERATED ALWAYS AS (`bigint_col` + 1) VIRTUAL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `bigint_virtual`;
-- @TIMER_END
