-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `ref_id`;
-- 测试删除被外键约束使用的子列时报错的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `ref_id` INT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD CONSTRAINT `fk_drop_col_self` FOREIGN KEY (`ref_id`) REFERENCES `{{TEST_TABLE_NAME}}` (`id_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP COLUMN `ref_id`;
-- @TIMER_END
