-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试枚举集合列更新后执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `enum_col` = 'bbb', `set_col` = '111,222' WHERE `id_col` % 3 = 1;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
