-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试普通数据量下执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
