-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试最终场景下执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_opt_final` (`date_col`,`time_col`);
UPDATE `{{TEST_TABLE_NAME}}` SET `date_col` = '2024-02-02', `time_col` = '02:02:02' WHERE `id_col` % 4 = 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
