-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试删除部分行后执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}` WHERE `id_col` % 2 = 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
