-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试更新并删除数据后执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = CONCAT('u_', COALESCE(`varchar_col`, '')) WHERE `id_col` % 3 = 0;
DELETE FROM `{{TEST_TABLE_NAME}}` WHERE `id_col` % 5 = 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
