-- OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- 测试插入额外行后执行 OPTIMIZE TABLE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`int_col`,`varchar_col`,`enum_col`,`set_col`) VALUES (101,'opt_a','aaa','111'),(102,'opt_b','bbb','222');
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
OPTIMIZE TABLE `{{TEST_TABLE_NAME}}`;
-- @TIMER_END
