-- UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 0 ORDER BY `id_col` DESC LIMIT 500;
-- 测试仅主键下 UPDATE ORDER BY id_col DESC LIMIT 500 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 0 ORDER BY `id_col` DESC LIMIT 500;
-- @TIMER_END
