-- UPDATE `{{TEST_TABLE_NAME}}` SET `enum_col` = 'bbb' WHERE `id_col` IS NOT NULL;
-- 测试仅主键下 UPDATE WHERE id_col IS NOT NULL 全表含 NULL 安全条件的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `enum_col` = 'bbb' WHERE `id_col` IS NOT NULL;
-- @TIMER_END
