-- UPDATE `{{TEST_TABLE_NAME}}` SET `datetime_col` = '2024-06-15 12:00:00' WHERE `id_col` < 100;
-- 测试仅主键下 UPDATE datetime_col WHERE id_col < 100 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `datetime_col` = '2024-06-15 12:00:00' WHERE `id_col` < 100;
-- @TIMER_END
