-- UPDATE `{{TEST_TABLE_NAME}}` SET `int_col` = CASE WHEN `id_col` % 3 = 0 THEN 0 WHEN `id_col` % 3 = 1 THEN 1 ELSE -1 END WHERE `id_col` IS NOT NULL;
-- 测试仅主键下 CASE 表达式 UPDATE int_col WHERE id_col IS NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `int_col` = CASE WHEN `id_col` % 3 = 0 THEN 0 WHEN `id_col` % 3 = 1 THEN 1 ELSE -1 END WHERE `id_col` IS NOT NULL;
-- @TIMER_END
