-- UPDATE `{{TEST_TABLE_NAME}}` SET `bigint_col` = NULL WHERE `id_col` IN (1, 2, 3, 4, 5);
-- 测试仅主键下 UPDATE 非索引列设为 NULL WHERE id_col IN 少量主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `bigint_col` = NULL WHERE `id_col` IN (1, 2, 3, 4, 5);
-- @TIMER_END
