-- UPDATE `{{TEST_TABLE_NAME}}` SET `year_col` = 2024 WHERE `id_col` BETWEEN 1 AND 10000;
-- 测试仅主键下 UPDATE WHERE id_col BETWEEN 大范围的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `year_col` = 2024 WHERE `id_col` BETWEEN 1 AND 10000;
-- @TIMER_END
