-- UPDATE `{{TEST_TABLE_NAME}}` SET `int_col` = 0 WHERE `id_col` BETWEEN 1 AND 100;
-- 测试仅主键下 UPDATE WHERE id_col BETWEEN 小范围的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `int_col` = 0 WHERE `id_col` BETWEEN 1 AND 100;
-- @TIMER_END
