-- UPDATE `{{TEST_TABLE_NAME}}` SET `char_col` = 'lim2' ORDER BY `id_col` LIMIT 2000;
-- 测试仅主键下 UPDATE ORDER BY id_col LIMIT 2000 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `char_col` = 'lim2' ORDER BY `id_col` LIMIT 2000;
-- @TIMER_END
