-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL KEY `idx_sp_point_key` (`point_key_col`);
-- 测试使用 KEY 同义词建立 POINT SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `point_key_col` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `point_key_col` = ST_GeomFromText('POINT(14 14)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `point_key_col` POINT SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL KEY `idx_sp_point_key` (`point_key_col`);
-- @TIMER_END
