-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multipolygon` (`multipolygon_col`);
-- 测试 MULTIPOLYGON 列建立 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `multipolygon_col` MULTIPOLYGON SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `multipolygon_col` = ST_GeomFromText('MULTIPOLYGON(((0 0,0 1,1 1,1 0,0 0)))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `multipolygon_col` MULTIPOLYGON SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multipolygon` (`multipolygon_col`);
-- @TIMER_END
