-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_dup_name` (`pt_dup`);
-- 测试重复 SPATIAL 索引名时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_dup` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_dup` = ST_GeomFromText('POINT(4 4)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_dup` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_dup_name` (`pt_dup`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_dup_name` (`pt_dup`);
-- @TIMER_END
