-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_geomcollection` (`geomcollection_col`);
-- 测试 GEOMETRYCOLLECTION 列建立 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `geomcollection_col` GEOMETRYCOLLECTION SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `geomcollection_col` = ST_GeomFromText('GEOMETRYCOLLECTION(POINT(1 1),LINESTRING(0 0,1 1))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `geomcollection_col` GEOMETRYCOLLECTION SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_geomcollection` (`geomcollection_col`);
-- @TIMER_END
