-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multi` (`pt_a`, `pt_b`);
-- 测试 SPATIAL 索引作用于多个空间列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_a` POINT SRID 0 NULL, ADD COLUMN `pt_b` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_a` = ST_GeomFromText('POINT(6 6)'), `pt_b` = ST_GeomFromText('POINT(7 7)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_a` POINT SRID 0 NOT NULL, MODIFY COLUMN `pt_b` POINT SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multi` (`pt_a`, `pt_b`);
-- @TIMER_END
