-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_prefix` (`pt_prefix`(10));
-- 测试 SPATIAL 索引指定前缀长度时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_prefix` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_prefix` = ST_GeomFromText('POINT(8 8)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_prefix` POINT SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_prefix` (`pt_prefix`(10));
-- @TIMER_END
