-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_point` (`pt_point`) USING RTREE;
-- 测试 POINT 列在 USING RTREE 组合下建立 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_point` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_point` = ST_GeomFromText('POINT(1 1)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_point` POINT SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_point` (`pt_point`) USING RTREE;
-- @TIMER_END
