-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multilinestring` (`multiline_col`);
-- 测试 MULTILINESTRING 列建立 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `multiline_col` MULTILINESTRING SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `multiline_col` = ST_GeomFromText('MULTILINESTRING((0 0,1 1),(2 2,3 3))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `multiline_col` MULTILINESTRING SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_multilinestring` (`multiline_col`);
-- @TIMER_END
