-- CREATE INDEX `idx_hash_not_supported` USING HASH ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- 测试 InnoDB CREATE INDEX显式指定 USING HASH 时的执行结果记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE INDEX `idx_hash_not_supported` USING HASH ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- @TIMER_END
