CREATE TABLE IF NOT EXISTS `{{BASE_TABLE_NAME}}` (
  `id_col` int AUTO_INCREMENT,
  `int_col` mediumint,
  `bigint_col` bigint,
  `year_col` year,
  `char_col` char(4),
  `tinyint_col` tinyint unsigned,
  `bool_col` tinyint(1),
  `smallint_col` smallint,
  `mediumint_col` mediumint unsigned,
  `decimal_col` decimal(25,5) unsigned,
  `float_col` float unsigned,
  `double_col` double unsigned,
  `date_col` date DEFAULT NULL,
  `datetime_col` datetime(6),
  `timestamp_col` timestamp NULL DEFAULT NULL,
  `time_col` time,
  `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `binary_col` binary(1) DEFAULT NULL,
  `varbinary_col` varbinary(255),
  `tinyblob_col` tinyblob,
  `blob_col` blob,
  `mediumblob_col` mediumblob,
  `longblob_col` longblob,
  `tinytext_col` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `text_col` text CHARACTER SET gbk COLLATE gbk_chinese_ci,
  `mediumtext_col` mediumtext CHARACTER SET utf8mb3 COLLATE utf8mb3_bin,
  `longtext_col` longtext CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  `enum_col` enum('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `bit_col` bit(8) DEFAULT b'10011001',
  `unsigned_int_col` int unsigned DEFAULT NULL,
  `unsigned_decimal_col` decimal(10,0) unsigned DEFAULT NULL,
  PRIMARY KEY (`id_col`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
