-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `varbinary_col` varbinary(255) NULL;
-- 测试将 varbinary_col 修改为 NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varbinary_col` = x'4243' WHERE `varbinary_col` IS NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `varbinary_col` varbinary(255) NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `varbinary_col` varbinary(255) NULL;
-- @TIMER_END
