-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `time_col` time NULL;
-- 测试将 time_col 修改为 NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `time_col` = '12:34:56' WHERE `time_col` IS NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `time_col` time NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `time_col` time NULL;
-- @TIMER_END
