-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `float_col` float unsigned NULL;
-- 测试将 float_col 修改为 NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `float_col` = 0 WHERE `float_col` IS NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `float_col` float unsigned NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `float_col` float unsigned NULL;
-- @TIMER_END
