-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `date_col` date NULL DEFAULT NULL;
-- 测试将 date_col 修改为 NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `date_col` = '2001-01-01' WHERE `date_col` IS NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `date_col` date NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `date_col` date NULL DEFAULT NULL;
-- @TIMER_END
