-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `date_col` `date_col` date DEFAULT NULL AFTER `time_col`;
-- 测试使用 CHANGE 将 date_col 调整到 time_col 之后的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `date_col` `date_col` date DEFAULT NULL AFTER `time_col`;
-- @TIMER_END
