-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bigint_col` bigint FIRST;
-- 测试使用 MODIFY 将 bigint_col 调整到表首的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bigint_col` bigint FIRST;
-- @TIMER_END
