-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bit_col` bit(8) DEFAULT b'10011001' AFTER `varbinary_col`;
-- 测试使用 MODIFY 将 bit_col 调整到 varbinary_col 之后的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bit_col` bit(8) DEFAULT b'10011001' AFTER `varbinary_col`;
-- @TIMER_END
