-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `set_col` `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin AFTER `enum_col`;
-- 测试使用 CHANGE 将 set_col 调整到 enum_col 之后的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `set_col` `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin AFTER `enum_col`;
-- @TIMER_END
