-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `datetime_col` datetime(6) AFTER `date_col`;
-- 测试使用 MODIFY 将 datetime_col 调整到 date_col 之后的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `datetime_col` datetime(6) AFTER `date_col`;
-- @TIMER_END
