-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `int_col` mediumint AFTER `varchar_col`;
-- 测试使用 MODIFY 将 int_col 调整到 varchar_col 之后的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `int_col` mediumint AFTER `varchar_col`;
-- @TIMER_END
