-- ALTER TABLE `{TEST_TABLE_NAME}` AUTO_INCREMENT = 10;
-- 测试将 AUTO_INCREMENT 设置为 10 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{TEST_TABLE_NAME}` AUTO_INCREMENT = 10;
-- @TIMER_END
