-- ALTER TABLE `{{TEST_TABLE_NAME}}` CONVERT TO CHARACTER SET utf8mb3 COLLATE utf8mb3_bin;
-- 测试将表转换为 utf8mb3 且排序规则为 utf8mb3_bin 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CONVERT TO CHARACTER SET utf8mb3 COLLATE utf8mb3_bin;
-- @TIMER_END
