-- ALTER TABLE `{{TEST_TABLE_NAME}}` CONVERT TO CHARACTER SET gbk COLLATE gbk_chinese_ci;
-- 测试将表转换为 gbk 且排序规则为 gbk_chinese_ci 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CONVERT TO CHARACTER SET gbk COLLATE gbk_chinese_ci;
-- @TIMER_END
