-- ALTER TABLE `{TEST_TABLE_NAME}` STATS_PERSISTENT=0, STATS_AUTO_RECALC=0, STATS_SAMPLE_PAGES=44;
-- STATS 组合 persist=0 recalc=0 pages=44

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{TEST_TABLE_NAME}` STATS_PERSISTENT=0, STATS_AUTO_RECALC=0, STATS_SAMPLE_PAGES=44;
-- @TIMER_END
