-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `decimal_col` decimal(25,5) unsigned NOT NULL;
-- 测试将 decimal_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `decimal_col` = 0 WHERE `decimal_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `decimal_col` decimal(25,5) unsigned NOT NULL;
-- @TIMER_END
