-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- 测试将 set_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `set_col` = '111' WHERE `set_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- @TIMER_END
