-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `year_col` year NOT NULL;
-- 测试将 year_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `year_col` = 2024 WHERE `year_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `year_col` year NOT NULL;
-- @TIMER_END
