-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `timestamp_col` timestamp NOT NULL;
-- 测试将 timestamp_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `timestamp_col` = '2001-01-01 01:02:03' WHERE `timestamp_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `timestamp_col` timestamp NOT NULL;
-- @TIMER_END
