-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- 测试将 varchar_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = 'notnull' WHERE `varchar_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `varchar_col` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- @TIMER_END
