-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bigint_col` bigint NOT NULL;
-- 测试将 bigint_col 修改为 NOT NULL 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `bigint_col` = 0 WHERE `bigint_col` IS NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bigint_col` bigint NOT NULL;
-- @TIMER_END
