-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `year_col` `year_col` smallint;
-- 测试将 year_col 从 year 改为 smallint 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `year_col` `year_col` smallint;
-- @TIMER_END
