-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `int_col` `int_col` int;
-- 测试将 int_col 从 mediumint 改为 int 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `int_col` `int_col` int;
-- @TIMER_END
