-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `bit_col` `bit_col` bit(16) DEFAULT b'1001100110011001';
-- 测试将 bit_col 从 bit(8) 改为 bit(16) 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `bit_col` `bit_col` bit(16) DEFAULT b'1001100110011001';
-- @TIMER_END
