-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `bool_col` `bool_col` bit(1) DEFAULT b'0';
-- 测试将 bool_col 从 tinyint(1) 改为 bit(1) 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `bool_col` `bool_col` bit(1) DEFAULT b'0';
-- @TIMER_END
