-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `bigint_col` DROP DEFAULT;
-- 测试删除 bigint_col 默认值的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `bigint_col` SET DEFAULT -1;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `bigint_col` DROP DEFAULT;
-- @TIMER_END
