-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `varbinary_col` DROP DEFAULT;
-- 测试删除 varbinary_col 默认值的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `varbinary_col` SET DEFAULT x'4243';
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `varbinary_col` DROP DEFAULT;
-- @TIMER_END
