-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME KEY `idx_rename_sp_old` TO `idx_rename_sp_new`;
-- 测试重命名 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_rename` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_rename` = ST_GeomFromText('POINT(11 11)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_rename` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_rename_sp_old` (`pt_rename`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME KEY `idx_rename_sp_old` TO `idx_rename_sp_new`;
-- @TIMER_END
