-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME INDEX `idx_missing_old` TO `idx_missing_new`;
-- 测试重命名不存在索引时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME INDEX `idx_missing_old` TO `idx_missing_new`;
-- @TIMER_END
