-- ALTER TABLE `{TEST_TABLE_NAME}` CHANGE COLUMN `varchar_col` `varchar_col` varchar(768) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
-- 测试将 varchar_col 扩展到 varchar(768) 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{TEST_TABLE_NAME}` CHANGE COLUMN `varchar_col` `varchar_col` varchar(768) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
-- @TIMER_END
