-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- 测试主键不存在时删除主键的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_only_secondary` (`varchar_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @TIMER_END
