-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- 测试空表复合主键删除的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
UPDATE `{{TEST_TABLE_NAME}}` SET `unsigned_int_col` = `id_col` WHERE `unsigned_int_col` IS NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `unsigned_int_col` INT UNSIGNED NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`id_col`, `unsigned_int_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @TIMER_END
