-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- 测试主键不存在且存在 SPATIAL 索引时删除主键的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_pk_only` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_pk_only` = ST_GeomFromText('POINT(19 19)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_pk_only` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_pk_sp_only` (`pt_pk_only`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @TIMER_END
