-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- 测试存在唯一索引时删除主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`varchar_col`) VALUES ('pku_a'), ('pku_b');
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD UNIQUE INDEX `idx_pk_unique` (`varchar_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @TIMER_END
