-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- 测试插入额外行后执行 ENGINE=InnoDB 空重建的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`int_col`,`varchar_col`,`enum_col`,`set_col`) VALUES (401,'eng_a','aaa','111'),(402,'eng_b','bbb','222');
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- @TIMER_END
