-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- 测试更新文本列后执行 ENGINE=InnoDB 空重建的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `text_col` = CONCAT(COALESCE(`text_col`, ''), 'eng_text') WHERE `id_col` % 4 = 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- @TIMER_END
