-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- 测试更新变长字符串后执行 ENGINE=InnoDB 空重建的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = CONCAT(COALESCE(`varchar_col`, ''), '_eng');
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- @TIMER_END
