-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- 测试删除大部分行后执行 ENGINE=InnoDB 空重建的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}` WHERE `id_col` % 10 <> 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENGINE=InnoDB;
-- @TIMER_END
