-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`date_col`, `time_col`);
-- 测试 date 与 time 列组合建立主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`date_col`, `time_col`) VALUES ('2024-04-01', '10:00:00'), ('2024-04-02', '11:00:00');
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `date_col` DATE NOT NULL, MODIFY COLUMN `time_col` TIME NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`date_col`, `time_col`);
-- @TIMER_END
