-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD CONSTRAINT `pk_enum_set` PRIMARY KEY (`enum_col`, `set_col`);
-- 测试 enum 与 set 列组合建立主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`enum_col`, `set_col`) VALUES ('aaa', '111'), ('bbb', '222');
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `enum_col` ENUM('aaa','bbb','ccc') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, MODIFY COLUMN `set_col` SET('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD CONSTRAINT `pk_enum_set` PRIMARY KEY (`enum_col`, `set_col`);
-- @TIMER_END
