-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`datetime_col`);
-- 测试 datetime 列建立主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`datetime_col`) VALUES ('2024-06-01 10:00:00.000000'), ('2024-06-02 10:00:00.000000');
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `datetime_col` DATETIME(6) NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`datetime_col`);
-- @TIMER_END
