-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY USING BTREE (`id_col`);
-- 测试删除原主键后重新添加单列 id 主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY USING BTREE (`id_col`);
-- @TIMER_END
