-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`time_col`, `char_col`);
-- 测试 time 与 char 列组合建立主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`time_col`, `char_col`) VALUES ('08:00:00', 'p081'), ('09:00:00', 'p091');
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `time_col` TIME NOT NULL, MODIFY COLUMN `char_col` CHAR(4) NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`time_col`, `char_col`);
-- @TIMER_END
