-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`int_col`);
-- 测试主键建立遇到空值数据时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`int_col`) VALUES (NULL), (9);
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`int_col`);
-- @TIMER_END
