-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`bool_col`, `year_col`);
-- 测试 bool 与 year 列组合建立主键的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`bool_col`, `year_col`) VALUES (0, 2022), (1, 2023);
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP PRIMARY KEY;
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `bool_col` TINYINT(1) NOT NULL, MODIFY COLUMN `year_col` YEAR NOT NULL;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD PRIMARY KEY (`bool_col`, `year_col`);
-- @TIMER_END
