-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_hash_not_supported` USING HASH (`varchar_col`);
-- 测试 InnoDB 普通索引显式指定 USING HASH 时的执行结果记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_hash_not_supported` USING HASH (`varchar_col`);
-- @TIMER_END
