-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_varchar_char` USING BTREE (`varchar_col`(32) DESC, `char_col` ASC) KEY_BLOCK_SIZE=8 COMMENT 'idx_varchar_char' INVISIBLE;
-- 测试 varchar 与 char 列在 USING BTREE、前缀、排序方向、KEY_BLOCK_SIZE、COMMENT、INVISIBLE 组合下的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_varchar_char` USING BTREE (`varchar_col`(32) DESC, `char_col` ASC) KEY_BLOCK_SIZE=8 COMMENT 'idx_varchar_char' INVISIBLE;
-- @TIMER_END
