-- ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- 测试由 CREATE FULLTEXT INDEX 创建索引后执行 DISABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
CREATE FULLTEXT INDEX `idx_disable_created_ft` ON `{{TEST_TABLE_NAME}}` (`varchar_col`, `text_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @TIMER_END
