-- ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- 测试 text、date、time 组合索引存在时执行 DISABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_disable_text_date_time` (`text_col`(20), `date_col`, `time_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @TIMER_END
