-- ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- 测试多个 INVISIBLE 索引存在时执行 DISABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_disable_inv_a` (`varchar_col`) INVISIBLE, ADD INDEX `idx_disable_inv_b` (`char_col`) INVISIBLE;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @TIMER_END
