-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `enum_col` SET DEFAULT 'bbb';
-- 测试将 enum_col 默认值设置为 'bbb' 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `enum_col` SET DEFAULT 'bbb';
-- @TIMER_END
