-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `date_col` SET DEFAULT '2001-01-01';
-- 测试将 date_col 默认值设置为 '2001-01-01' 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `date_col` SET DEFAULT '2001-01-01';
-- @TIMER_END
