-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `smallint_col` SET DEFAULT -12;
-- 测试将 smallint_col 默认值设置为 -12 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `smallint_col` SET DEFAULT -12;
-- @TIMER_END
