-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `decimal_col` SET DEFAULT 123.45000;
-- 测试将 decimal_col 默认值设置为 123.45000 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `decimal_col` SET DEFAULT 123.45000;
-- @TIMER_END
