-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `binary_col` SET DEFAULT x'41';
-- 测试将 binary_col 默认值设置为 x'41' 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER COLUMN `binary_col` SET DEFAULT x'41';
-- @TIMER_END
