-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHARACTER SET = utf8mb3;
-- 测试将表字符集指定为 utf8mb3 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHARACTER SET = utf8mb3;
-- @TIMER_END
