-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHARACTER SET = latin1 COLLATE = latin1_bin;
-- 测试将表字符集指定为 latin1 且排序规则为 latin1_bin 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHARACTER SET = latin1 COLLATE = latin1_bin;
-- @TIMER_END
