-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DATETIME GENERATED ALWAYS AS (NOW()) STORED;
-- 测试使用非确定性函数作为生成列表达式时新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DATETIME GENERATED ALWAYS AS (NOW()) STORED;
-- @TIMER_END
