-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT CHECK (`z` > 0);
-- 测试带列级 CHECK 约束的列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT CHECK (`z` > 0);
-- @TIMER_END
