-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARBINARY(32) NULL AFTER `binary_col`;
-- 测试使用 AFTER 子句在指定列后新增 VARBINARY 列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARBINARY(32) NULL AFTER `binary_col`;
-- @TIMER_END
