-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0.00;
-- 测试带 UNSIGNED 属性和默认值的 DECIMAL 列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0.00;
-- @TIMER_END
