-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NULL INVISIBLE;
-- 测试显式新增 INVISIBLE 隐藏列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NULL INVISIBLE;
-- @TIMER_END
