-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` SET('a','b','c') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'a,c';
-- 测试带字符集、排序规则和多值默认值的 SET 列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` SET('a','b','c') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'a,c';
-- @TIMER_END
