-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NOT NULL;
-- 测试在非空表上新增无默认值的 NOT NULL 列时的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NOT NULL;
-- @TIMER_END
