-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
-- 测试带微秒精度和 CURRENT_TIMESTAMP(6) 默认值的 DATETIME 列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
-- @TIMER_END
