-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(16) NOT NULL DEFAULT (UPPER('mix'));
-- 测试使用确定性默认表达式新增字符列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(16) NOT NULL DEFAULT (UPPER('mix'));
-- @TIMER_END
