-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD `z` BIGINT NOT NULL DEFAULT 0;
-- 测试省略 COLUMN 关键字时新增 BIGINT 非空默认值列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD `z` BIGINT NOT NULL DEFAULT 0;
-- @TIMER_END
