-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NOT NULL PRIMARY KEY;
-- 测试在已有主键表上以内联 PRIMARY KEY 方式新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT NOT NULL PRIMARY KEY;
-- @TIMER_END
