-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT NOT NULL AUTO_INCREMENT;
-- 测试未显式声明键约束时新增 AUTO_INCREMENT 列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT NOT NULL AUTO_INCREMENT;
-- @TIMER_END
