-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIT(16) NOT NULL DEFAULT b'0000000011110000';
-- 测试带二进制默认值的 BIT 列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIT(16) NOT NULL DEFAULT b'0000000011110000';
-- @TIMER_END
