-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` ENUM('x','y','z') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'x';
-- 测试带字符集、排序规则和默认值的 ENUM 列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` ENUM('x','y','z') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'x';
-- @TIMER_END
