-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(32) NULL VISIBLE COMMENT 'visible z column';
-- 测试显式 VISIBLE 与 COMMENT 组合下新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(32) NULL VISIBLE COMMENT 'visible z column';
-- @TIMER_END
