-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(260) GENERATED ALWAYS AS (CONCAT(COALESCE(`varchar_col`, ''), '-', COALESCE(`char_col`, ''))) VIRTUAL;
-- 测试基于现有字符列表达式生成的 VIRTUAL 生成列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(260) GENERATED ALWAYS AS (CONCAT(COALESCE(`varchar_col`, ''), '-', COALESCE(`char_col`, ''))) VIRTUAL;
-- @TIMER_END
