-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT AFTER `not_exists_col`;
-- 测试 AFTER 指向不存在列时新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT AFTER `not_exists_col`;
-- @TIMER_END
