-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT GENERATED ALWAYS AS (`id_col` + 1) VIRTUAL;
-- 测试生成列表达式引用 AUTO_INCREMENT 基列时新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` INT GENERATED ALWAYS AS (`id_col` + 1) VIRTUAL;
-- @TIMER_END
