-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT NOT NULL AUTO_INCREMENT UNIQUE;
-- 测试带 AUTO_INCREMENT 和 UNIQUE 约束的列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT NOT NULL AUTO_INCREMENT UNIQUE;
-- @TIMER_END
