-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(20) NULL DEFAULT 'ea' ENGINE_ATTRIBUTE='{\"stage\":\"ddl\"}' SECONDARY_ENGINE_ATTRIBUTE='';
-- 测试带 ENGINE_ATTRIBUTE 与 SECONDARY_ENGINE_ATTRIBUTE 属性新增列的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` VARCHAR(20) NULL DEFAULT 'ea' ENGINE_ATTRIBUTE='{\"stage\":\"ddl\"}' SECONDARY_ENGINE_ATTRIBUTE='';
-- @TIMER_END
