-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT GENERATED ALWAYS AS (COALESCE(`bigint_col`, 0) + COALESCE(`unsigned_int_col`, 0)) STORED;
-- 测试基于数值表达式生成的 STORED 生成列新增执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `z` BIGINT GENERATED ALWAYS AS (COALESCE(`bigint_col`, 0) + COALESCE(`unsigned_int_col`, 0)) STORED;
-- @TIMER_END
