-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- 测试 bit 与 timestamp 组合索引在 DISABLE 后执行 ENABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_enable_bit_ts` (`bit_col`, `timestamp_col`);
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- @TIMER_END
