-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- 测试同时存在 FULLTEXT 与 SPATIAL 索引时执行 ENABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD FULLTEXT INDEX `idx_enable_both_ft` (`varchar_col`, `text_col`);
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_enable_both` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_enable_both` = ST_GeomFromText('POINT(22 22)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_enable_both` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_enable_both_sp` (`pt_enable_both`);
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- @TIMER_END
