-- ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- 测试仅存在唯一索引时执行 ENABLE KEYS 的行为记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`varchar_col`) VALUES ('ek_u1'), ('ek_u2');
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD UNIQUE INDEX `idx_enable_unique` (`varchar_col`);
ALTER TABLE `{{TEST_TABLE_NAME}}` DISABLE KEYS;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ENABLE KEYS;
-- @TIMER_END
