-- UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 1 WHERE ABS(`bigint_col`) BETWEEN 0 AND 1000 LIMIT 500;
-- 测试表达式索引下 UPDATE WHERE ABS(bigint_col) BETWEEN 范围 LIMIT 500 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_upd_expr` ((ABS(`bigint_col`)));
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 1 WHERE ABS(`bigint_col`) BETWEEN 0 AND 1000 LIMIT 500;
-- @TIMER_END
