-- ALTER TABLE {{TEST_TABLE_NAME}} ADD INDEX idx_varchar(varchar_col);
-- 测试 {{TEST_TABLE_NAME}} 对 varchar_col 新增索引的执行时间

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_varchar` (`varchar_col`);
-- @TIMER_END
