-- CREATE UNIQUE INDEX `idx_unique_abs_bigint` ON `{{TEST_TABLE_NAME}}` ((ABS(`bigint_col`)));
-- 测试函数表达式CREATE UNIQUE INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DELETE FROM `{{TEST_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`bigint_col`) VALUES (101), (202);
-- @PREPARE_END

-- @TIMER_START
CREATE UNIQUE INDEX `idx_unique_abs_bigint` ON `{{TEST_TABLE_NAME}}` ((ABS(`bigint_col`)));
-- @TIMER_END
