-- CREATE SPATIAL INDEX `idx_sp_line` ON `{{TEST_TABLE_NAME}}` (`line_col`);
-- 测试 LINESTRING 列CREATE SPATIAL INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `line_col` LINESTRING SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `line_col` = ST_GeomFromText('LINESTRING(0 0,1 1)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `line_col` LINESTRING SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_line` ON `{{TEST_TABLE_NAME}}` (`line_col`);
-- @TIMER_END
