-- CREATE SPATIAL INDEX `idx_sp_nullable` ON `{{TEST_TABLE_NAME}}` (`pt_nullable`);
-- 测试 CREATE SPATIAL INDEX作用于可空空间列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_nullable` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_nullable` = ST_GeomFromText('POINT(5 5)');
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_nullable` ON `{{TEST_TABLE_NAME}}` (`pt_nullable`);
-- @TIMER_END
