-- CREATE SPATIAL INDEX `idx_sp_line_nullable` ON `{{TEST_TABLE_NAME}}` (`line_nullable_col`);
-- 测试 CREATE SPATIAL INDEX作用于可空 LINESTRING 列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `line_nullable_col` LINESTRING SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `line_nullable_col` = ST_GeomFromText('LINESTRING(1 1,2 2)');
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_line_nullable` ON `{{TEST_TABLE_NAME}}` (`line_nullable_col`);
-- @TIMER_END
