-- CREATE SPATIAL INDEX `idx_sp_multipoint_dup` ON `{{TEST_TABLE_NAME}}` (`multipoint_dup_col`);
-- 测试重复 MULTIPOINT CREATE SPATIAL INDEX 名时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `multipoint_dup_col` MULTIPOINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `multipoint_dup_col` = ST_GeomFromText('MULTIPOINT((3 3),(4 4))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `multipoint_dup_col` MULTIPOINT SRID 0 NOT NULL;
CREATE SPATIAL INDEX `idx_sp_multipoint_dup` ON `{{TEST_TABLE_NAME}}` (`multipoint_dup_col`);
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_multipoint_dup` ON `{{TEST_TABLE_NAME}}` (`multipoint_dup_col`);
-- @TIMER_END
