-- CREATE SPATIAL INDEX `idx_sp_geometry` ON `{{TEST_TABLE_NAME}}` (`geometry_col`);
-- 测试 GEOMETRY 列CREATE SPATIAL INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `geometry_col` GEOMETRY SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `geometry_col` = ST_GeomFromText('POINT(3 3)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `geometry_col` GEOMETRY SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_geometry` ON `{{TEST_TABLE_NAME}}` (`geometry_col`);
-- @TIMER_END
