-- CREATE SPATIAL INDEX `idx_sp_nonspatial` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- 测试 CREATE SPATIAL INDEX作用于非空间列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_nonspatial` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- @TIMER_END
