-- CREATE SPATIAL INDEX `idx_sp_polygon` ON `{{TEST_TABLE_NAME}}` (`polygon_col`);
-- 测试 POLYGON 列CREATE SPATIAL INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `polygon_col` POLYGON SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `polygon_col` = ST_GeomFromText('POLYGON((0 0,0 1,1 1,1 0,0 0))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `polygon_col` POLYGON SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_polygon` ON `{{TEST_TABLE_NAME}}` (`polygon_col`);
-- @TIMER_END
