-- CREATE SPATIAL INDEX `idx_sp_multipoint` ON `{{TEST_TABLE_NAME}}` (`multipoint_col`);
-- 测试 MULTIPOINT 列建立 CREATE SPATIAL INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `multipoint_col` MULTIPOINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `multipoint_col` = ST_GeomFromText('MULTIPOINT((1 1),(2 2))');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `multipoint_col` MULTIPOINT SRID 0 NOT NULL;
-- @PREPARE_END

-- @TIMER_START
CREATE SPATIAL INDEX `idx_sp_multipoint` ON `{{TEST_TABLE_NAME}}` (`multipoint_col`);
-- @TIMER_END
