-- ALTER TABLE `{{TEST_TABLE_NAME}}` ROW_FORMAT=DYNAMIC;
-- ROW_FORMAT 轮换 11

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ROW_FORMAT=DYNAMIC;
-- @TIMER_END
