-- ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `set_col` `set_col_r1` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
-- 测试使用 CHANGE 将 set_col 重命名为 set_col_r1 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` CHANGE COLUMN `set_col` `set_col_r1` set('111','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
-- @TIMER_END
