-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_rename_case_16`;
-- 测试目标表名较长时将表重命名为 test_table_rename_case_16 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_rename_case_16`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_rename_case_16`;
-- @TIMER_END
