-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r20`;
-- 测试最终场景下将表重命名为 test_table_r20 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_rn_final` (`date_col`,`time_col`);
UPDATE `{{TEST_TABLE_NAME}}` SET `date_col` = '2024-04-04', `time_col` = '04:04:04' WHERE `id_col` % 4 = 0;
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_r20`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r20`;
-- @TIMER_END
