-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r04`;
-- 测试有联合索引时将表重命名为 test_table_r04 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_rn_multi` (`year_col`, `unsigned_decimal_col`);
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_r04`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r04`;
-- @TIMER_END
