-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r07`;
-- 测试插入额外数据后将表重命名为 test_table_r07 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` (`int_col`,`varchar_col`,`enum_col`,`set_col`) VALUES (201,'rn_a','aaa','111'),(202,'rn_b','bbb','222');
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_r07`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r07`;
-- @TIMER_END
