-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r17`;
-- 测试有多个辅助索引时将表重命名为 test_table_r17 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_rn_a` (`varchar_col`), ADD INDEX `idx_rn_b` (`date_col`), ADD INDEX `idx_rn_c` (`bit_col`);
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_r17`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r17`;
-- @TIMER_END
