-- ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r19`;
-- 测试组合更新删除后将表重命名为 test_table_r19 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = CONCAT(COALESCE(`varchar_col`, ''), '_combo');
DELETE FROM `{{TEST_TABLE_NAME}}` WHERE `id_col` % 5 = 0;
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}_r19`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` RENAME TO `{{TEST_TABLE_NAME}}_r19`;
-- @TIMER_END
