-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('333','222','111') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL;
-- 测试重排 set_col 成员顺序的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('333','222','111') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL;
-- @TIMER_END
