-- ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('111','444','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL;
-- 测试向 set_col 中间插入新成员的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `set_col` set('111','444','222','333') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL;
-- @TIMER_END
