-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_text_vis` INVISIBLE;
-- 测试 text 前缀索引切换为 INVISIBLE 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_text_vis` (`text_col`(20));
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_text_vis` INVISIBLE;
-- @TIMER_END
