-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_vis_same_invisible` INVISIBLE;
-- 测试已经为 INVISIBLE 的普通索引再次设置 INVISIBLE 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_vis_same_invisible` (`varchar_col`) INVISIBLE;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_vis_same_invisible` INVISIBLE;
-- @TIMER_END
