-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `PRIMARY` INVISIBLE;
-- 测试 ALTER INDEX 作用于主键时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `PRIMARY` INVISIBLE;
-- @TIMER_END
