-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_sp_vis_back` VISIBLE;
-- 测试 SPATIAL 索引从 INVISIBLE 切回 VISIBLE 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_vis_back` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_vis_back` = ST_GeomFromText('POINT(17 17)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_vis_back` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_sp_vis_back` (`pt_vis_back`) INVISIBLE;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_sp_vis_back` VISIBLE;
-- @TIMER_END
