-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_abs_vis` INVISIBLE;
-- 测试函数索引切换为 INVISIBLE 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_abs_vis` ((ABS(`bigint_col`)));
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_abs_vis` INVISIBLE;
-- @TIMER_END
