-- ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_bit_ts_vis` VISIBLE;
-- 测试 bit 与 timestamp 组合索引从 INVISIBLE 切回 VISIBLE 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_bit_ts_vis` (`bit_col`, `timestamp_col`) INVISIBLE;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ALTER INDEX `idx_bit_ts_vis` VISIBLE;
-- @TIMER_END
