-- UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 1 ORDER BY `varchar_col` DESC LIMIT 1000;
-- 测试逆序索引 varchar_col DESC 下 UPDATE ORDER BY varchar_col DESC LIMIT 1000 的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_upd_desc_vc` (`varchar_col` DESC);
-- @PREPARE_END

-- @TIMER_START
UPDATE `{{TEST_TABLE_NAME}}` SET `bool_col` = 1 ORDER BY `varchar_col` DESC LIMIT 1000;
-- @TIMER_END
