-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP INDEX `idx_drop_created`;
-- 测试删除由 CREATE INDEX 创建的索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
CREATE INDEX `idx_drop_created` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP INDEX `idx_drop_created`;
-- @TIMER_END
