-- ALTER TABLE `{{TEST_TABLE_NAME}}` DROP INDEX `idx_drop_spatial`;
-- 测试删除 SPATIAL 索引的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD COLUMN `pt_drop` POINT SRID 0 NULL;
UPDATE `{{TEST_TABLE_NAME}}` SET `pt_drop` = ST_GeomFromText('POINT(10 10)');
ALTER TABLE `{{TEST_TABLE_NAME}}` MODIFY COLUMN `pt_drop` POINT SRID 0 NOT NULL;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD SPATIAL INDEX `idx_drop_spatial` (`pt_drop`);
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` DROP INDEX `idx_drop_spatial`;
-- @TIMER_END
