-- CREATE FULLTEXT INDEX `idx_ft_varchar` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- 测试单列 varchar CREATE FULLTEXT INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_varchar` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- @TIMER_END
