-- CREATE FULLTEXT INDEX `idx_ft_prefix` ON `{{TEST_TABLE_NAME}}` (`varchar_col`(20), `text_col`(30));
-- 测试 CREATE FULLTEXT INDEX指定前缀长度时的执行结果记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_prefix` ON `{{TEST_TABLE_NAME}}` (`varchar_col`(20), `text_col`(30));
-- @TIMER_END
