-- CREATE FULLTEXT INDEX `idx_ft_missing_col` ON `{{TEST_TABLE_NAME}}` (`missing_col`);
-- 测试 CREATE FULLTEXT INDEX引用不存在列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_missing_col` ON `{{TEST_TABLE_NAME}}` (`missing_col`);
-- @TIMER_END
