-- CREATE FULLTEXT INDEX `idx_ft_dup_name` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- 测试重复 CREATE FULLTEXT INDEX名时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD FULLTEXT INDEX `idx_ft_dup_name` (`text_col`);
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_dup_name` ON `{{TEST_TABLE_NAME}}` (`varchar_col`);
-- @TIMER_END
