-- CREATE FULLTEXT INDEX `idx_ft_char_text_inv` ON `{{TEST_TABLE_NAME}}` (`char_col`, `text_col`) INVISIBLE;
-- 测试 char 与 text 列在 INVISIBLE 组合下建立 CREATE FULLTEXT INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_char_text_inv` ON `{{TEST_TABLE_NAME}}` (`char_col`, `text_col`) INVISIBLE;
-- @TIMER_END
