-- CREATE FULLTEXT INDEX `idx_ft_longtext` ON `{{TEST_TABLE_NAME}}` (`longtext_col`) COMMENT 'ft_longtext';
-- 测试单列 longtext CREATE FULLTEXT INDEX的执行情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_longtext` ON `{{TEST_TABLE_NAME}}` (`longtext_col`) COMMENT 'ft_longtext';
-- @TIMER_END
