-- CREATE FULLTEXT INDEX `idx_ft_blob_invalid` ON `{{TEST_TABLE_NAME}}` (`blob_col`);
-- 测试 CREATE FULLTEXT INDEX作用于 blob 列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
CREATE FULLTEXT INDEX `idx_ft_blob_invalid` ON `{{TEST_TABLE_NAME}}` (`blob_col`);
-- @TIMER_END
