-- ALTER TABLE `{{TEST_TABLE_NAME}}` ADD FULLTEXT INDEX `idx_ft_invalid_type` (`int_col`);
-- 测试 FULLTEXT 索引作用于非字符列时的报错记录

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD FULLTEXT INDEX `idx_ft_invalid_type` (`int_col`);
-- @TIMER_END
