-- ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- 测试多次更新同一列后执行 ALTER TABLE FORCE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = RPAD(COALESCE(`varchar_col`, ''), 40, 'y');
UPDATE `{{TEST_TABLE_NAME}}` SET `varchar_col` = TRIM(TRAILING 'y' FROM COALESCE(`varchar_col`, ''));
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- @TIMER_END
