-- ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- 测试更新时间列后执行 ALTER TABLE FORCE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
UPDATE `{{TEST_TABLE_NAME}}` SET `datetime_col` = '2024-05-05 05:05:05.123456' WHERE `id_col` % 2 = 1;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- @TIMER_END
