-- ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- 测试有联合索引时执行 ALTER TABLE FORCE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_force_multi` (`year_col`, `unsigned_decimal_col`);
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- @TIMER_END
