-- ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- 测试最终场景下执行 ALTER TABLE FORCE 的情况

-- @PREPARE_START
DROP TABLE IF EXISTS `{{TEST_TABLE_NAME}}`;
ALTER TABLE `{{TEST_TABLE_NAME}}` ADD INDEX `idx_force_final` (`date_col`,`time_col`);
UPDATE `{{TEST_TABLE_NAME}}` SET `date_col` = '2024-06-06', `time_col` = '06:06:06' WHERE `id_col` % 4 = 0;
CREATE TABLE `{{TEST_TABLE_NAME}}` LIKE `{{BASE_TABLE_NAME}}`;
INSERT INTO `{{TEST_TABLE_NAME}}` SELECT * FROM `{{BASE_TABLE_NAME}}`;
-- @PREPARE_END

-- @TIMER_START
ALTER TABLE `{{TEST_TABLE_NAME}}` FORCE;
-- @TIMER_END
